### PR TITLE
Switched 'he' to 'they'

### PR DESCRIPTION
**Pull request by AndrewCarterUK**

### CODE REVIEW

**Comment by samdark** [comment]
Coordinator is a single person. Thus "he". Right?

**Comment by quantumpacket** [comment]
Why was this closed? I have to agree with the usage of "they", or at least modify it so it's not specific to a male, unless for some odd reason the coordinator is a male only position.

**Comment by samdark** [comment]
It's not about gender. It's about calling a single person "they".

**Comment by quantumpacket** [comment]
https://www.oxforddictionaries.com/words/he-or-she-versus-they

**Comment by michaelcullum** [comment]
+1 to the PR. 'they' can be used to refer to a singular person. Also, we can have more than one editor.

**Comment by samdark** [comment]
OK. Wasn't aware of this way of using English. Thanks!

**Pull request merged**
