### PR TITLE
PSR-7 typo

### PR DESCRIPTION
**Pull request by cebe**
I'm a bit late to the party but this should be fixed :)

### CODE REVIEW

**Comment by joshdifabio** [comment]
The original text is correct; punctuation _should_ go inside quotation marks[1].

[1] http://www.grammarbook.com/punctuation/quotes.asp (see 3a)

**Comment by samdark** [comment]
Doesn't it depend on if it's British or American English? It is valid as is for American variant for sure...

**Comment by joshdifabio** [comment]
The existing text is correct according to British convention. I can't speak for Americans, but according to the link I posted it's standard both in US and British English for punctuation to go within quotation marks.

**Comment by samdark** [comment]
Indeed. Wikipedia seems to mislead about it. Both BBC and Guardian guides are suggesting comma inside of quotation marks. @cebe it seems original is correct.

**Comment by cebe** [comment]
weird, did not know about this rule and looks strange to me. but okay if it is correct, leave it as is.

**Pull request closed without merging**
