### PR TITLE
PSR7 : no more set and add methods

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
@weierophinney may be you could verify this and merge ?

**Comment by weierophinney** [comment]
@pmjones Changes are good; please merge. :-)

**Comment by xabbuh** [comment]
By the way, this is the same as #423.

**Comment by harikt** [comment]
@xabbuh nice. I didn't find it. I will close the PR, for credits should be given for FIFO ;) .

**Pull request closed without merging**
