### PR TITLE
fix #325 - README-pt_BR.md

### PR DESCRIPTION
**Pull request by rogeriopradoj**
[pt_BR] Create README-pt_BR.md, starting with original EN
[pt_BR] Translate README into Brazilian Portuguese
[pt_BR] Enhance translation of README-pt_BR (thanks @andreia!)

List of notes:
- https://github.com/php-fig/fig-standards/pull/325#discussion-diff-27341117
- https://github.com/php-fig/fig-standards/pull/325#discussion-diff-27341162
- https://github.com/php-fig/fig-standards/pull/325#discussion-diff-27341482
- https://github.com/php-fig/fig-standards/pull/325#issuecomment-88280023

Signed-off-by: Rogerio Prado de Jesus <rogeriopradoj@gmail.com>

### CODE REVIEW

**Comment by rogeriopradoj** [comment]
Please, @henriquemoody, ask someone to take a look on this PR, cause has just one commit (squashed).

It will close #325 automatically and merged!

Thanks

**Comment by henriquemoody** [comment]
Thanks, @rogeriopradoj!

The content is exactly the same of #325. 

@philsturgeon, can you merge it?

BTW, we created a fork (https://github.com/php-brasil/fig-standards) to keep the discussions about our language outside this repository.

**Comment by philsturgeon** [comment]
Tests are failing. Chase @pmjones for merges I'm not meant to go here anymore.

**Comment by henriquemoody** [comment]
Thanks and I'm sorry for pinging you.

**Comment by philsturgeon** [comment]
Not a problem :)

-- 
Phil

**Comment by rogeriopradoj** [comment]
Hey guys, the tests failing are because there is no tests! Maybe a problem with [Circle CI](https://circleci.com/gh/php-fig/fig-standards/109), not?

Anyway, I think it's not a problem about this PR. Hey @pmjones, could you take a look? Tks!

**Pull request closed without merging**
