### PR TITLE
Make the wording against underscore prefixes stronger

### PR DESCRIPTION
**Pull request by Crell**
As discussed on list. This is still being discussed I think but here's the PR for it if we go that route.

### CODE REVIEW

**Comment by samdark** [comment]
Could cause less adoption rate but :+1: from me.

**Comment by samdark** [comment]
@michaelcullum, @KorvinSzanto ?

**Comment by michaelcullum** [comment]
:+1:

**Comment by KorvinSzanto** [comment]
:+1:

**Comment by samdark** [comment]
Thanks!

**Comment by dereuromark** [comment]
:-1: This is a nogo.
Those underscores can be useful to show the visbility on e.g. PRs and other (diff) tools where you do not have the direct visibility via IDE.

    return $this->_doSth();

etc.

**Comment by Jean85** [comment]
I'm sorry but this part is already an established standard in PSR-2, see: https://www.php-fig.org/psr/psr-2/#42-properties

**Comment by dereuromark** [comment]
Yeah, with SHOULD NOT, which means you can ignore it for good reasons.

**Comment by Jean85** [comment]
My personal opinion is that that is a bad practice. Changing the visibility of a property shouldn't require a rename, for example. Hence, consistency is hard to maintain without that rule.

**Pull request merged**
