### PR TITLE
Update reference to PSR-2 to PSR-12

### PR DESCRIPTION
**Pull request by skylerfenn**
PSR-2 is now deprecated.

### CODE REVIEW

**Comment by Jean85** [comment]
This is advisable, but since it's a `MUST`, we cannot merge it due to the fact that it's not backward compatible, and it would possibly break the spec for an implementing library.

**Comment by benedmunds** [comment]
Bumping this @Jean85

**Comment by Jean85** [comment]
Wow, damn be the pandemic, I definitely dropped this!

I'll call the vote.

**Comment by skylerfenn** [comment]
> There's a typo in this but the vote has now started - there shouldn't be a comma after 'and'

Fixed!

**Review by samdark — APPROVED** [review]

**Review by yuparach99 — APPROVED** [review]

**Review by Jean85 — APPROVED** [review]
Sorry I'm VERY late!

Both votes are passed! :+1: 

https://groups.google.com/g/php-fig/c/GK-fjLdQFBk
https://groups.google.com/g/php-fig/c/FfJcCx4nHx0

**Pull request merged**
