### PR TITLE
Add errata detailing addition of scalar type hints for PSR-11 (ContainerInterface)

### PR DESCRIPTION
**Pull request by weierophinney**
See:

- https://github.com/php-fig/container/pull/27
- https://github.com/php-fig/container/pull/28

### CODE REVIEW

**Comment by weierophinney** [comment]
Ping @moufmouf — are you okay with this?

**Comment by dragoonis** [comment]
Looks decent 👍

**Comment by Jean85** [comment]
On hold until #1216 goes through.

**Review by ashnazg — APPROVED** [review]

**Review by Jean85 — APPROVED** [review]
Vote has passed.

**Pull request merged**
