### PR TITLE
Markdown Syntax Highlighting

### PR DESCRIPTION
**Pull request by dragoonis**

### CODE REVIEW

**Comment by michaelcullum** [comment]
👍

**Comment by schnittstabil** [comment]
Just out of interest; as far as I known and according to [the github markdown documentation](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting), the correct syntax is as follows, isn't it?

```diff
- ``` php
+ ```php

- ~~~php
+ ```php
```

**Comment by michaelcullum** [comment]
Jekyll requires tildes. @reinink Could explain better

**Comment by schnittstabil** [comment]
I believe this should be better fixed by some jekyll configuration; anyway, thanks @michaelcullum.

**Pull request merged**
