### PR TITLE
Update PSR-1 Headings

### PR DESCRIPTION
**Pull request by MayBeTall**
Using the same format as the other recommended changes, like #910.

### CODE REVIEW

**Comment by MayBeTall** [comment]
Quick question - would you guys mind if I reformatted all the approved PSRs? I notice they are coming in one-by-one and the approval for each must be tedious on your side.

**Comment by KorvinSzanto** [comment]
@MayBeTall that's probably a better way to do it. We're waiting on @michaelcullum to approve for this to be merged.

**Comment by Jean85** [comment]
This has conficts with the target branch. @MayBeTall are you willing to fix those?

**Comment by samdark** [comment]
Closing since it's already like that in master.

**Pull request closed without merging**
