### PR TITLE
PSR-18: Change introduction to be more specific to clients

### PR DESCRIPTION
**Pull request by kelunik**
Servers also send HTTP messages. This PSR is about sending requests and receiving responses.

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you

**Comment by sagikazarmark** [comment]
I'm not quite sure I completely agree with this change. I agree with the intent, but I think something like `sending HTTP requests and receiving HTTP responses` describes better what an HTTP client does.

**Comment by dbu** [comment]
depends on whether you look from the implementor point of view, or from the using application pov.

for the implementor, its about sending requests and receiving responses. for the user, its requesting resources. (hm, except for POST/PUT) when the main thing is triggering something on the other end...)

i think i like your proposal even better, mark. can you please do a new PR to adjust this again, so we can discuss that?

**Comment by sagikazarmark** [comment]
Sure #986

**Pull request merged**
