### PR TITLE
Fix examples in `PSR-7-http-message-meta.md`

### PR DESCRIPTION
**Pull request by WinterSilence**
base on #1193

### CODE REVIEW

**Review by drupol — APPROVED** [review]

**Comment by vdelau** [comment]
I suppose the document pre-dates PSR-18, but it might be good to align the meta document with it. Decision lies with the editor.

**Review by dbu — APPROVED** [review]
these are examples, i don't see any problem with the change. and agree that it would make sense to align with PSR-18.

**Review by weierophinney — APPROVED** [review]

**Comment by weierophinney** [comment]
@vdelau I've approved, and was editor on this one... but it shows a code owner is required before it can be merged.

**Review by Jean85 — APPROVED** [review]
I can approve it, no issues.

**Pull request merged**
