### PR TITLE
[PSR16] Added missing slash on DateInterval

### PR DESCRIPTION
**Pull request by prisis**

### CODE REVIEW

**Comment by dragoonis** [comment]
Fine with me.

**Comment by dragoonis** [comment]
@afolson @michaelcullum +1 this please.

**Comment by sbol-coolblue** [comment]
What would be required to move this forward?

**Comment by bkrukowski** [comment]
+1

**Comment by shieldo** [comment]
Polite, additional ping as reminder :)

**Comment by gsdevme** [comment]
Any chance this could be moved forward? it causes static analysis to trip up as no `DateInterval` exists in the scope of `Psr\SimpleCache`

**Comment by michaelcullum** [comment]
This change should be propagated across to the interface library.

**Comment by sstok** [comment]
Can we a new tag please? ❤️

**Pull request merged**
