### PR TITLE
[PSR-11] Warn about Service Locator usage

### PR DESCRIPTION
**Pull request by mnapoli**
This was in a pull request in the "container-interop" fork that ended up being merged. I'm opening this PR to bring back those changes here. In the future we'll work on this repository to avoid these kind of problems and to be more transparent about the work we do.

The goal of these changes is to explicitly document that `ContainerInterface` should not be used as a service locator. The lengthy explanations are in the META document while the standard only contains a paragraph to keep it short and simple.

FYI I'll reopen https://github.com/container-interop/fig-standards/pull/14 against this repo afterwards.

ping @php-fig/psr-11 @moufmouf

### CODE REVIEW

**Comment by mnapoli** [comment]
@moufmouf with the new system I need a 👍  from a member of @php-fig/psr-11 to merge :)

And btw thanks for merging https://github.com/container-interop/fig-standards/pull/14 I see it's now included in this PR, so after merging this our fork will be completely in sync with this repository and we can work on this one exclusively.

**Comment by moufmouf** [comment]
@mnapoli You're welcome!

That's fairly cool to be able to work directly on this repository. Also, I've just been added as a PHP-FIG's member, and I don't think that "pullapprove" has detected yet that I can approve the PR.

So far, I see:

> Approval required by 1 of: mnapoli, pmjones

But I'm of course :+1: for merging this.

**Comment by mnapoli** [comment]
If you go directly on https://pullapprove.com/php-fig/fig-standards/pull-request/805/ you can't approve it manually?

**Comment by mnapoli** [comment]
Indeed you are not even showing up there, ping @pmjones?

**Comment by pmjones** [comment]
@mnapoli sorry for the delay, looking at it now :-)

**Comment by pmjones** [comment]
What's with the "pull approve" thing now?

**Comment by mnapoli** [comment]
It allows us to work on the main repo but only change PSRs we are working on, I admit it's the first time I use that

**Comment by michaelcullum** [comment]
@moufmouf It's waiting on you to accept your invite to the PSR-11 team. :)

@pmjones Please read the [mailing list](https://groups.google.com/d/msg/php-fig/fU0wd7YQVgg/NV2_BWKRBgAJ) and #790 (which you should have got a notification about). It was implemented after people were pushing changes directly to the main repo (that than were later decided to be reverted) or not checking with Editors before merging things.

**Pull request merged**
