### PR TITLE
[PSR-7] fix leftover null reason phrase

### PR DESCRIPTION
**Pull request by Tobion**
Follow up to 5506a9c2a453969aaabb4e359c41d2bef938bc0b

ping @weierophinney

### CODE REVIEW

**Comment by weierophinney** [comment]
@simensen and/or @pmjones — this can be merged anytime.

**Comment by simensen** [comment]
We should not merge anything of any level until after the vote closes.

**Comment by simensen** [comment]
(Otherwise ok!)

**Comment by Tobion** [comment]
Rebased

**Comment by Tobion** [comment]
ping

**Comment by weierophinney** [comment]
@simensen This can be merged now; do you still have merge rights?

**Comment by Tobion** [comment]
Hello?

**Pull request merged**
