### PR TITLE
Will the folding of the code?

### PR DESCRIPTION
**Pull request by korenevskiy**
Will the folding of the code?
Such as C#, operator "#region"
```
<?php
#region Comment
echo 'its working';
#endregion
```
After that, the code folding in the "#region".
```
<?php
#region Comment and work fold code
```
This hidden code is working for PHP.

### CODE REVIEW

**Comment by samdark** [comment]
Seems the pull request isn't right.

**Comment by samdark** [comment]
If you want to start a discussion please post to mailing list: https://groups.google.com/forum/#!forum/php-fig

**Comment by samdark** [comment]
@michaelcullum please close the pull request.

**Comment by michaelcullum** [comment]
Indeed. This pull request seems to have some rouge commits. Please rebase and resubmit or create a discussion topic on the mailing list.

**Pull request closed without merging**
