### PR TITLE
Don't require a forward slash for exception example

### PR DESCRIPTION
**Pull request by michaelcullum**
Clarify that forward slash is not required.

### CODE REVIEW

**Comment by michaelcullum** [comment]
@samdark @KorvinSzanto Merge ASAP please

**Comment by KorvinSzanto** [comment]
I'm not sure that this resolves the point brought up on this list, why are we disallowing use statements for classes in the root namespace? https://3v4l.org/QSnaf

**Comment by GrahamCampbell** [comment]
I think this example is meant to be when you're not in a namespace.

**Comment by michaelcullum** [comment]
Indeed and it was due to comments of people saying they refuse to always use \Exception when they don't need to when actually the PSR never required the forward slash, it just disallowed the import.

`use Exception; throw new Exception();` is riddled with redundant/dead code and doesn't help clarify understanding at all, in fact it makes it possibly decreases readability as you have to check the two places whereas `throw new \Exception();` is so much easier to understand.

**Comment by KorvinSzanto** [comment]
I'm not sure where I stand on the issue, it sounds a little heavy handed to me tbh. I just wanted to make sure we're really addressing the issue.

**Comment by michaelcullum** [comment]
I've added a small clarification on here too. I didn't mean to add two things to the PR but oh well.

It's a common question and certainly within scope. Also most projects don't import root classes anyway.

**Comment by simensen** [comment]
> Also most projects don't import root classes anyway.

I think this would be a case where it would actually make sense to do a survey. :) I don't know that I've seen consistency here anywhere and honestly I'm not sure that it matters too much.

For me, personally, I'd prefer people always `use` things and never have a leading `\` anywhere for the sake of consistency.

Requiring me to always `throw \RuntimeException` or worse yet `extend \RuntimeException` is probably going to get a "PSR-12 (without requiring the leading `\` for root classes)" label.

**Comment by KorvinSzanto** [comment]
@simensen I agree. I'm not sure we need to make a judgement on this at all.

**Comment by markstory** [comment]
@simensen I also think having explicit `use` gives code more consistency and makes the imports in any given file simpler to follow. 

Exempting root classes from `use` means the recommended standards are more complex as documenting when to use `use` is required.

**Comment by pmjones** [comment]
@simensen Is exactly right -- this is not a PHP-7-specific requirement, and as such is amenable to survey.

**Comment by judgej** [comment]
Personally I import any namespaces are are not in the classes namespace. That way you can see right at the top what namespaces that class uses. This includes \Exception, and project aliases such as Laravel's \Log, \Input etc.

Also - can we stop talking about *forward* slashes.

* / is a forward slash.
* \\ is a backward slash

**Comment by judgej** [comment]
> When wishing to declare strict types in files containing markup outside PHP opening and closing tags MUST, on the first line, include an opening php tag, the strict types declaration and closing tag.

IMO this statement reads more like a work instruction, telling you what to do. It should just describe the end result, what the relationships are between constructs. TBH, I can't even follow what this sentence is saying anyway - it is just confusing even after reading five times. Can it be split up into smaller chunks?

**Pull request merged**
