### PR TITLE
[PSR3] Translation in italian

### PR DESCRIPTION
**Pull request by Jean85**
I've translated the PSR3 document in italian.
I didn't found any particular indication or styleguide for it, so I've somewhat followed what was done for PSR2.

Please review it! Thanks!

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
@mlocati if you have some freetime, do you mind taking a look at this?

**Comment by mlocati** [comment]
@Jean85 If you're looking for generic translation guidelines you could read http://tp.linux.it/buona_traduzione.html: it contains a widely adopted set of Italian translation rules.

**Comment by Jean85** [comment]
@mlocati thanks! I've read that, I'm almost ok, I've slipped just on the uppercase stressed letters, and I've fixed it!

**Comment by Jean85** [comment]
Ok, fixed as @mlocati (partially) suggested. See https://github.com/php-fig/fig-standards/pull/621#commitcomment-13106246 for comments

**Comment by KorvinSzanto** [comment]
@mlocati, you're awesome thank you!

**Comment by mlocati** [comment]
> @mlocati, you're awesome thank you!

@KorvinSzanto Hey Korvin, are you going to lean Italian? :wink:

**Comment by eleftrik** [comment]
@Jean85, there's a small typo in PSR-2 coding style guide: 

correttori automatici di **sile**

Grazie ;-)

**Comment by Jean85** [comment]
I did not translated that, but no problem, I'll fix it!

**Comment by samdark** [comment]
So it it ready to be merged?

**Comment by Jean85** [comment]
I think it is... @mlocati , did you review it all? It's ok?

**Comment by Jean85** [comment]
So? @samdark @mlocati

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
