### PR TITLE
Removing the delegate lookup feature from PSR-11

### PR DESCRIPTION
**Pull request by moufmouf**
Following [discussion on the mailing list](https://groups.google.com/forum/#!searchin/php-fig/delegate%7Csort:relevance/php-fig/9YAFG4Xw2zo/uTeLRWTKAwAJ), there seems to be a consensus that the delegate lookup feature (which is actually a design pattern) might be worked on in another PSR (or may be not needed as a PSR at all as it is only a design pattern).

### CODE REVIEW

**Comment by weierophinney** [comment]
Not sure what I need to do to get pullapprove to pass? :+1: maybe? or LGTM?

**Comment by michaelcullum** [comment]
Just put 👍 as the message (nothing else).

**Comment by weierophinney** [comment]
:+1:

**Comment by weierophinney** [comment]
> Just put  as the message (nothing else).

I couldn't find that information even in the pullapprove overview or features... Is there a way to make that more obvious in the future, @michaelcullum ?

**Comment by michaelcullum** [comment]
@weierophinney GH keeps saying they'll open up approvals/reviews on their API, then pullapprove will use that. Until then it's actually regex defined in the repo which is why it's not on pull approve's site. You're welcome to add things to it (https://github.com/php-fig/fig-standards/blob/master/.pullapprove.yml#L2) other than that I'm not sure where we could document this although I do try to generally inform people with commit access that it's there when they get given access.

**Comment by KorvinSzanto** [comment]
@moufmouf Do you mind resolving the conflicts for this pull request?

**Comment by moufmouf** [comment]
@KorvinSzanto Done, conflicts resolved.

**Comment by michaelcullum** [comment]
As a general note, this will probably require a review period reset so you might want to get this merged ASAP if you are still planning on doing this on FIG 2.

**Pull request merged**
