### PR TITLE
Update the status of PSR-6

### PR DESCRIPTION
**Pull request by mnapoli**
If I'm not mistaken it is currently in voting phase.

### CODE REVIEW

**Comment by samdark** [comment]
It is.

**Comment by michaelcullum** [comment]
Voting is not a stage. It's Review then Accepted.
https://github.com/php-fig/fig-standards/blob/master/bylaws/004-psr-workflow.md#23-review

--
Michael C

**Comment by samdark** [comment]
According to bylaws, yes. But see the footer of that page. There's `V = Voting` and it's actually what happens now.

**Comment by mnapoli** [comment]
Yep that was confusing on the website (see http://www.php-fig.org/psr/#numerical-index)

**Comment by samdark** [comment]
I think it's an important info for community watching php-fig and should be like that despite our internal bylaws.

**Pull request merged**
