### PR TITLE
Update PSR-2-coding-style-guide.md

### PR DESCRIPTION
**Pull request by xtrasmal**
Starting with the namespace on the first line makes that whole <?php thing less obnoxious.

### CODE REVIEW

**Comment by milesj** [comment]
I disagree :+1:

**Comment by pmoust** [comment]
PSR-2 is final.
That said, :-1: , I find it less readable anyway.

**Comment by pmjones** [comment]
No.

**Comment by xtrasmal** [comment]
Ok great :D anyways. Thanks for considering. Now it's free for all!!!

**Pull request closed without merging**
