### PR TITLE
[PSR-7] Fixed quotes

### PR DESCRIPTION
**Pull request by hason**

### CODE REVIEW

**Comment by ockcyp** [comment]
:+1:

**Comment by samdark** [comment]
:+1:

**Comment by Tobion** [comment]
:+1:

**Comment by simensen** [comment]
I need to make sure that we can fix this type of thing in accepted PSR's. One would think we should be able to do so but I don't recall exactly what we are allowed to do. I know there are a few of these that have stacked up so hopefully we can get around to it in the next week or so.

**Comment by pmjones** [comment]
Changes of no substance, such as typos that do not change meaning, are fair game.

**Comment by simensen** [comment]
@pmjones so you'd feel comfortable merging this type of request? if so, i'd say let's merge it.

**Pull request merged**
