### PR TITLE
Apparently this needed to be written down

### PR DESCRIPTION
**Pull request by philsturgeon**
It seems fairly obvious, and the FIG Secretaries considered it to be fairly obvious, but [Paul Jones was freaking out again](https://groups.google.com/forum/#!topic/php-fig/gMnU02lU1D0).

The FIG does not need to get into the habit of making bylaws for every damn decision the secretaries make, but this should calm the situation down a bit.

### CODE REVIEW

**Comment by kayladnls** [comment]
:+1:

**Comment by rask** [comment]
Okay, I am a userland developer, but this needs to be asked:

Why is someone in the FIG board (and voting) while their votes are being nulled? Would this mean that they should not be on the board at all? Why not expell the said party from voting in the first place?

**Comment by pmjones** [comment]
Paul Jones is a fan of votes being counted unless they are expressly to be discounted, and not leaving it to whim. Call the defense of that principled position a "freak-out" if you wish.

For my part, I have no objection to this being explicitly specified.

**Comment by tedivm** [comment]
@philsturgeon- I yelled at Paul a week ago for his calling you out unnecessarily, and now I'll do the same to you. This thread could have been opened in a lot more professional manner. Perhaps you guys should both just vow never to directly refer to the other person, as it would solve a lot of issues.

I also don't think this solved the problem that came up on the list. The issue isn't about whether members should be allowed to vote on their own expulsion. The question is whether secretaries can remove voting members rights when there is nothing in the bylaws that allows this. This change you are proposing solves part of the problem, but there should be another line that makes it explicit that all members can vote on all issues unless the bylawys specifically say they can't. Otherwise this issue will just crop up again when the Secretaries decide to restrict people from voting.

**Comment by pmjones** [comment]
> Perhaps you guys should both just vow never to directly refer to the other person, as it would solve a lot of issues.

Fine with me; if Phil can keep his mouth shut about me, even from behind a Twitter block, I can certain let his stay beneath my notice as well.

**Comment by michaelcullum** [comment]
I think we can all just be a bit nicer to each other. Discussion of this can continue on the mailing list.

**Pull request closed without merging**
