### PR TITLE
[PRSR-6] fix return type

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by samdark** [comment]
Why? `boolean` is valid type, isn't it?

**Comment by xabbuh** [comment]
For two reasons: `bool` is used everywhere else in this document and `bool` is what you can use for type hints in PHP 7.

**Comment by samdark** [comment]
You can use `boolean` for both type hinting and type casting in PHP.

**Comment by milesj** [comment]
@samdark No you can't? http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

**Comment by samdark** [comment]
Wat... it could be used for type casting but not for scalar type hinting in PHP 7. I think it's a bug. Will report it to PHP team...

**Comment by xabbuh** [comment]
IIRC the initial proposal wanted to support both, but current implementations don't seem to support that: https://3v4l.org/qXBeR

**Comment by samdark** [comment]
https://bugs.php.net/bug.php?id=70833

**Comment by dragoonis** [comment]
I'm merging this only because the rest of the PSR-6 document has 'bool' in it. Nothing to do with PHP7.

**Comment by samdark** [comment]
Yes. Makes sense.

**Pull request merged**
