### PR TITLE
Update headings

### PR DESCRIPTION
**Pull request by Aliance**
Before:

---

After:

### CODE REVIEW

**Comment by Aliance** [comment]
Sorry, did not mentioned. Duplicates #910

**Comment by Aliance** [comment]
@KorvinSzanto @michaelcullum @rdeutz hi everyone. What about this pr?

**Comment by KorvinSzanto** [comment]
We're just waiting on a thumbs up from @michaelcullum

**Comment by jrfnl** [comment]
@michaelcullum An approve here would be much appreciated. I was trying to link to some of the sections and found I couldn't because of the headings not being marked up as such. :heart_eyes_cat:

**Comment by Aliance** [comment]
After merging it with master, seems that all my proposed changes was merged in #934.

**Pull request closed without merging**
