### PR TITLE
rewording the timezone faq

### PR DESCRIPTION
**Pull request by ashnazg**

### CODE REVIEW

**Comment by ashnazg** [comment]
Ping @cseufert

**Review by cseufert — APPROVED** [review]
I think this makes the intent much clearer, thanks @ashnazg

**Review by cseufert — APPROVED** [review]

**Comment by cseufert** [comment]
@Jean85 are you able to merge this PR?

**Comment by ashnazg** [comment]
@cseufert , as Editor, do you feel everything is ready to move to vote?

**Comment by cseufert** [comment]
@ashnazg I was thinking the same thing, I think its as ready as its going to be.

**Comment by ashnazg** [comment]
@cseufert ok cool, then as the Editor, it's up to you to call the Readiness Vote with the Working Group.

Use this example (@Crell 's readiness vote on PSR-14 [https://groups.google.com/g/php-fig/c/NhJ_O4JkYG4/m/vBNBij2-FAAJ]) on how to start the email thread.  You only need to cover that you're calling the vote, that it's only the Working Group that can vote, and give the two week timeline for the voting period.

**Comment by ashnazg** [comment]
@cseufert if you need me to, I can draft the readiness vote email, and get it to you to send... it just has to come from you as the Editor per the bylaw.

**Comment by ashnazg** [comment]
@cseufert , hit me at my php.net addy and I'll send you a prepared draft.

**Pull request merged**
