### PR TITLE
Update PSR-2-coding-style-guide.md

### PR DESCRIPTION
**Pull request by DiegoYungh**
I almost thought they were duplicates so I highlighted the class/method names.

### CODE REVIEW

**Comment by michaelcullum** [comment]
It's not code and it's fine as it is I think.

**Comment by GrahamCampbell** [comment]
:-1: this change is incorrect imo

**Comment by samdark** [comment]
Agree.

**Comment by michaelcullum** [comment]
@samdark Can we close this then please?

**Comment by michaelcullum** [comment]
Ah nevermind then. heh.

**Pull request closed without merging**
