### PR TITLE
[PSR-7] unify wording and clarify relative path is in HTTP context

### PR DESCRIPTION
**Pull request by Tobion**
Follow up to #543

### CODE REVIEW

**Comment by weierophinney** [comment]
:+1: — falls under clarification, and good to merge after acceptance is completed. /ping @simensen and/or @pmjones .

**Comment by Tobion** [comment]
Rebased

**Comment by Tobion** [comment]
ping

**Comment by weierophinney** [comment]
@simensen good to merge; do you still have rights?

**Pull request merged**
