### PR TITLE
[PSR-15] Add syntax highlighting & fix markdown bullet list bug

### PR DESCRIPTION
**Pull request by atanvarno69**
* Add syntax highlighting in section 4.2.1 code block
* Use alternate markdown syntax to prevent bullet list rendering bug, see #866 for the same issue/fix in PSR-11's documentation

### CODE REVIEW

**Comment by weierophinney** [comment]
IIRC, the syntax used by the various PSRs is due to the usage of Jekyll to publish the website. As such, I'm unsure if we can accept the changes.

Pinging @michaelcullum @reinink for clarification...

**Comment by reinink** [comment]
Nope, this should be fine. I'd just say be consistent with what's being done elsewhere in this repo, which I believe this change is doing.

**Comment by michaelcullum** [comment]
@php-fig/psr-15

**Comment by shadowhand** [comment]
:+1:

**Pull request merged**
