### PR TITLE
Logger description small fix.

### PR DESCRIPTION
**Pull request by tititi123**
Add php tag for syntax highlighting, add space after explanation mark.

### CODE REVIEW

**Comment by michaelcullum** [comment]
👍

**Comment by michaelcullum** [comment]
PSR-2 doesn't say have spaces after ! operators although I'm fine with the `<?php` change.

**Comment by tititi123** [comment]
@michaelcullum ok, i changed this.

**Comment by michaelcullum** [comment]
:+1:

**Pull request merged**
