### PR TITLE
[PSR12] Add section for Anonymous Classes. 

### PR DESCRIPTION
**Pull request by KorvinSzanto**
This adds a section describing anonymous classes.

### CODE REVIEW

**Comment by KorvinSzanto** [comment]
Not sure how to write up parameters yet

**Comment by michaelcullum** [comment]
Can you rebase out the intellJ stuff? Also this needs to go above the PSR links, they should all group at the bottom of the file. Otherwise I'm :+1: to this.

**Comment by KorvinSzanto** [comment]
Moved the links and squashed the commits.

**Comment by michaelcullum** [comment]
:+1: This can be merged please @samdark

**Pull request merged**
