### PR TITLE
Fixup php code to use immutable message interface

### PR DESCRIPTION
**Pull request by bburnichon**
`$message->setHeader()` and `$message->addHeader()` do not exists.

### CODE REVIEW

**Comment by bburnichon** [comment]
@weierophinney This PR belongs to PSR-7. I forgot to indicate it in the title.

**Comment by weierophinney** [comment]
@pmjones - good to merge.

**Comment by weierophinney** [comment]
Duplicated by #423 and #424 ! :)

**Comment by bburnichon** [comment]
We have to be consistent but 3 PRs for the same change is a little too much. :) @pmjones will have to choose the merge winner.

**Comment by harikt** [comment]
@bburnichon 409 is first. So this could be merged :+1:  .

**Pull request closed without merging**
