### PR TITLE
Remove Drupal

### PR DESCRIPTION
**Pull request by theodoreb**

### CODE REVIEW

**Review by drupol — APPROVED** [review]
LGTM

**Comment by drupol** [comment]
Hi @theodoreb ! Long time no see :) hope you're doing well !

**Comment by vdelau** [comment]
This is not a simple PR change, as it is governed by the by-laws. The situation of not having a Project Representative for a Member Project is not really covered in the by-laws.

I think the best course of action would be an email to the mailing list from a verifiable project representative to trigger:

> A Member Project may resign from the PHP FIG in writing to an official FIG public channel. Once such a statement is published and the resignation is confirmed by a secretary, a PHP project immediately ceases to be a Member Project.

Obviously, we'd rather see a new Project Representative from Drupal. That would have to be announced by the Member Project in a similar fashion. 

Alternatively, a vote has to be triggered in the CC to remove Drupal as a member project. My proposal for such a vote would be to "remove Drupal as a Member Project 'in good standing'".

**Comment by goba** [comment]
@vdelau Is this queue an "official FIG public channel"? 

@theodoreb is one of the Drupal core committers and submitted this PR following a discussion between the Drupal core committers. I also one of the Drupal core committers.

**Comment by catch56** [comment]
I'm also a Drupal core committer.

We submitted a PR because that was the process that Symfony (successfully) followed. https://github.com/php-fig/fig-standards/pull/1120

**Comment by Jean85** [comment]
> @vdelau Is this queue an "official FIG public channel"?

The official channel is the mailing list: https://groups.google.com/forum/#!forum/php-fig

> We submitted a PR because that was the process that Symfony (successfully) followed. #1120

Yes, but in that case the choice was announced, and the PR was opened by the representative.
Can you link here your credentials as Drupal members? We will relay the matter to the Core Committee.

**Comment by catch56** [comment]
Core committers are listed in the first section of this document: https://api.drupal.org/api/drupal/core%21MAINTAINERS.txt/10.0.x

**Comment by dbuytaert** [comment]
+1 from me.  (I'm Drupal's Project Lead.)

**Comment by weierophinney** [comment]
Out of curiousity... what is the reason behind Drupal choosing to leave FIG? I would be interested in knowing, to understand what we could be doing differently for the ecosystem, and/or where projects do or do not see value in membership.

Thanks!

**Comment by shadowhand** [comment]
I have requested a Core Committee vote on this matter: https://groups.google.com/g/php-fig/c/GFX3tL9R8eU

**Comment by arturpanteleev** [comment]
Hm...Could you tell me about the reasons of this decision?

**Pull request merged**
