### PR TITLE
Update PSR-1-basic-coding-standard.md

### PR DESCRIPTION
**Pull request by MrFibunacci**
Misspelling of `<?`

### CODE REVIEW

**Comment by rob006** [comment]
This is not misspelling, this is "short echo" syntax: http://php.net/manual/en/function.echo.php

**Comment by drupol** [comment]
> 
> 
> This is not misspelling, this is "short echo" syntax: http://php.net/manual/en/function.echo.php

Yes I know, but I think that in this context, it's not the right syntax.

**Comment by rob006** [comment]
> If `<?=` is accepted as a tag opening, then it must be fixed in other places in the document.

What places? This document does not have any places where using short-echo would make sense. The whole point of this rule is to disallow `<?`.

**Comment by drupol** [comment]
On line 17 and 37.

**Pull request closed without merging**
