### PR TITLE
New PSR: RDF interfaces

### PR DESCRIPTION
**Pull request by k00ni**
Hello. I would like to propose new interfaces representing RDF terms (https://www.w3.org/RDF/), to have a basement for framework/library interoperability.

### Motivation

There are currently 5 RDF-libraries for PHP available ([EasyRdf](https://github.com/njh/easyrdf), [Erfurt](https://github.com/AKSW/Erfurt), [hardf](https://github.com/pietercolpaert/hardf), [ARC2](https://github.com/semsol/arc2) and [Saft](https://github.com/SaftIng/Saft)). Each implements different areas with various quality and feature-coverage. Combined, they provide a rich feature-set from RDF data handling, serialization and parsing to database access. Therefore it is important, that each library uses the same data model for RDF data to allow data interchange. Furthermore, having those interfaces could help developers to write compatible applications.

### Background

The proposed interfaces and example implementations are based on a PHP RDF framework i maintain (Saft). This means, that they are battle tested and i have already created (basic) converters for all major frameworks.

Link to **Google Groups** [**thread**](https://groups.google.com/forum/#!topic/php-fig/Z1dds-mBRrE).

### CODE REVIEW

**Comment by michaelcullum** [comment]
Indeed, if you'd like to have a chat about this more, feel free to drop me a DM on twitter (@michaelcullumuk) and we can exchange emails/find a time for a quick call to talk over it.

**Comment by k00ni** [comment]
@michaelcullum: Because i didn't heard from you after my mail, i will try it this way. 

Stefano Toressi posted a list of Core Committee members [here](https://github.com/stefanotorresi/fig-standards/blob/5804f440faf78cde4b0c21b6bcd2cee64cf04778/personnel.md). Should i ask each one of them directly to sponsor my PSR? Or do you know someone, who would be interested in that?

**Comment by Jean85** [comment]
I fear that we already have a lot on our plates right now; we are restarting 2 abandoned PSR and an other 3 are on draft or review phase. 

The best channel to push this forward could be the mailing list though...

**Comment by SerafimArts** [comment]
Hmmm... I can’t imagine why it is needed in PSR. Imho: The "mission" of PSR is basically the development of solutions for integrating _popular library functions_ into applications.

In this case, your solution is not very popular. With the same success, it was possible to offer interfaces for generating Excel reports or working with PDF. Too rare special case.

// this is my personal opinion as a bystander, who by pure chance came to this page with the PR and has no weight in the decisions. =)

**Comment by vdelau** [comment]
Hi @k00ni, is this still something you'd like to pursue, or can this PR be closed?

**Comment by k00ni** [comment]
Thanks for getting back. This PR can be closed.

**Pull request closed without merging**
