### PR TITLE
Update PSR-2-coding-style-guide.md

### PR DESCRIPTION
**Pull request by njutn95**
Make headlines more visible by making them bold.

### CODE REVIEW

**Comment by njutn95** [comment]
This is how it currently looks like, as you can see the header "2. General" is very small compared to subheader "2.1. Basic Coding Standard":

psr-2

And this is how the header looks like with my proposed change: 

psr-2-2

**Comment by jkufner** [comment]
That Markdown markup is wrong.

```
## Heading
-----
```

Means `<h2>Heading</h2><hr>` instead of expected `<h2>Heading</h2>`. Notice the second line below the heading in your screenshot.

The problem is somewhere else. Maybe cached old stylesheet or some bug.

**Comment by njutn95** [comment]
Oh, I see the second line now. Kinda went unnoticed as the brightness on the other monitor is lowered so I forgot on the horizontal rule.

**Comment by KorvinSzanto** [comment]
This is waiting on approval from @michaelcullum

**Comment by Jean85** [comment]
This needs a rebase. @njutn95 are you willing to do it?

**Comment by Jean85** [comment]
Neverming, closing this in favor of #910.

**Pull request closed without merging**
