### PR TITLE
s/move/moveTo/

### PR DESCRIPTION
**Pull request by weierophinney**
Per @Crell, this change clarifies the purpose of the method by renaming it to `moveTo()`. Additionally, the method argument name was changed to `$targetPath` to make the change completely clear.

### CODE REVIEW

**Comment by Crell** [comment]
$targetPath is even better, yes!

One other question: What is that path relative to?  I would implicitly assume it's script-root-relative, as is PHP's default, but that's not clear.  (And script-root-relative is always messy anyway.)

**Comment by weierophinney** [comment]
@Crell —

> What is that path relative to?

That would be dependent on the `$targetPath` value and the current working directory. If the `$targetPath` is absolute, you write to that; otherwise, you write relative to the current working directory.

**Comment by Crell** [comment]
That should be made explicit, I think. Even if it's explicit to "the same logic as what PHP's move() function does" (which I think is the point).

**Comment by Crell** [comment]
+1!

**Comment by weierophinney** [comment]
@simensen and/or @pmjones — Ready to merge! I'll create updates later on http-message once all issues are addressed.

**Pull request merged**
