### PR TITLE
[PSR-12] Uppercasing key word

### PR DESCRIPTION
**Pull request by Jean85**
Minor typo. The `MUST NOT` keyword should always be uppercase.

### CODE REVIEW

**Comment by michaelcullum** [comment]
@KorvinSzanto 👍

**Comment by samdark** [comment]
@KorvinSzanto, @rdeutz is it good to merge?

**Comment by KorvinSzanto** [comment]
Err I'm not sure what github did here, give me a second.

**Comment by KorvinSzanto** [comment]
@Jean85 You'll have to forgive me, I tried to resolve conflicts via the github interface and added a typo in there :S I tried adding another merge in manually but it's acting odd in my local environment and I don't want to risk adding something dumb to the git history. Do you mind remaking this change and opening a new pull request?

**Comment by samdark** [comment]
If we agree on the change, I can do it myself... just a minute.

**Comment by samdark** [comment]
https://github.com/php-fig/fig-standards/pull/877

**Pull request closed without merging**
