### PR TITLE
Add explicit nullable types to PSR-17

### PR DESCRIPTION
**Pull request by alexandre-daubois**
In order to make [this one pass](https://github.com/php-fig/http-factory/pull/17) 🙂

### CODE REVIEW

**Review by Jean85 — CHANGES_REQUESTED** [review]
Changes LGTM :+1: 

Let's wait for @shadowhand review and call for a vote

**Review by shadowhand — APPROVED** [review]

**Comment by alexandre-daubois** [comment]
Thank you for checking this David!

**Comment by Jean85** [comment]
@shadowhand we need you to call a vote to approve this, but before we need to fix https://github.com/php-fig/http-factory/pull/16 by bumping to PHP 7.1+. Let me know how you want to proceed.

**Comment by alexandre-daubois** [comment]
I'm fine providing the updated PR if the author of the current one is not able to, cc @Ayesh 🙂

**Review by samdark — APPROVED** [review]

**Comment by shadowhand** [comment]
> @shadowhand we need you to call a vote to approve this.

The vote has been called.

**Review by mbniebergall — APPROVED** [review]
Passed voting

**Review by Jean85 — APPROVED** [review]

**Pull request merged**
