### PR TITLE
Make InvalidArgumentException explcitly extend CacheException

### PR DESCRIPTION
**Pull request by Crell**
As discussed on list. Also reorders the exceptions to make it a bit cleaner to read.

### CODE REVIEW

**Comment by simensen** [comment]
:+1: I'd like to get feedback from @dragoonis & @tedivm before accepting this. By accepting this, I mean dropping PSR-6 from [REVIEW] long enough to merge these and put it back up for [REVIEW] again.

**Comment by simensen** [comment]
@dragoonis @tedivm Can I get a yay or nay on this one?

**Comment by dragoonis** [comment]
@simensen  Nay. Communicated on mailing list. /cc @Crell

**Comment by Crell** [comment]
I rebased this branch to account for #595.  

@dragoonis As noted on the list, we're not adding any classes.  All we're doing here is making one interface extend the other.  If you have an objection to that, please explain. Otherwise let's get this merged so we can get back to Review.

**Comment by dragoonis** [comment]
@Crell Let's merge this. I will merge this so you're not merging your own work, that okay?

**Comment by Crell** [comment]
:thumbsup:

**Comment by dragoonis** [comment]
@Crell done.

**Pull request merged**
