### PR TITLE
Fix incorrect syntax for markdown link in PSR-6 meta document

### PR DESCRIPTION
**Pull request by dregad**

### CODE REVIEW

**Comment by samdark** [comment]
What's incorrect exactly?

**Comment by dregad** [comment]
See the patch... Markdown link syntax is `[text](url)` (URL in parenthesis), not `[text][url]` (square brackets)

**Comment by samdark** [comment]
Ah, right :)

**Comment by michaelcullum** [comment]
:+1:

@Crell

**Pull request merged**
