### PR TITLE
[PSR-17] Remove unnecessary returns from docblocks

### PR DESCRIPTION
**Pull request by shadowhand**
Strict typing already defines the return type.

Plus a couple of minor corrections.

### CODE REVIEW

**Comment by ashnazg** [comment]
Normally I agree with omitting tags when the code signature can provide the info...

However, in a *spec*, maybe the redundancy is good, in that it is some *reinforcing* documentation alongside the spec code.  If the tag and code are out of sync, it is a visible warning that the spec is somehow amiss and in need of deeper review.  Without it, an incorrect value might be on the code signature, and not be spotted as incorrect.

**Comment by slavcodev** [comment]
> Having the @return in the docblock could lead to conflicts between the type defined by the code and the type defined in the docblock. There is no value to duplicating the return type.

Sounds incorrect. Which conflicts are you talking about? DocBlock describes interface, interface is explicit by the specific return type. No matter what implementation exactly the method returns.

**Comment by shadowhand** [comment]
```
/**
  * @return FooInterface
  */
function getFoo(): BarInterface;
```

Which one is invalid? Return type should be defined in code, not docblock.

**Comment by slavcodev** [comment]
DocBlock is not the code, it is docs source and should describes the code.

> Which one is invalid? Return type should be defined in code, not docblock.
Of course in this case the documentation is broken, this is mistake and it is responsibility of devs to keep it correct.

**Comment by ashnazg** [comment]
Let's say the true, correct spec is this:
```
function getFoo(): BarInterface;
```

Let's say the spec in draft looks like this:
```
function getFoo(): FooInterface;
```

When reviewing the draft, that could easily be missed as incorrect.

But, if the spec insisted on using all tags to back up the code signatures too, then it's easy to spot the mismatch:
```
/**
 * @return BarInterface
 */
function getFoo(): FooInterface;
```

That's my only point.  In the case of a *spec*, perhaps the duplication can be a check-and-balance type of reinforcement-of-correctness, where the _narrative_ has to match the _signature_.

It's just a suggestion...

**Comment by shadowhand** [comment]
Docblocks are used to generate documentation *when the code does not provide it*. With return typing, there is no need for `@return` documentation. Suggesting that docblocks somehow provide verification of intent is, at best, misguided.

**Pull request merged**
