### PR TITLE
Update PSR-11-container.md

### PR DESCRIPTION
**Pull request by tspencer244**
Copy the wording given in the container meta document.

### CODE REVIEW

**Comment by tspencer244** [comment]
https://www.php-fig.org/psr/psr-11/meta/#4-recommended-usage-container-psr-and-the-service-locator

image

https://www.php-fig.org/psr/psr-11/

image

I found this wording confusing and wasn't sure whether it was recommending usage of service locator pattern or not recommending it :confused:

**Comment by Crell** [comment]
Already approved PSRs are not subject to change.  They are frozen.

Using a service locator pattern is not-good, and should be avoided most of the time.  There's a few exceptions around lazy factories where it may be necessary, but those are fairly few.

**Comment by tspencer244** [comment]
Sorry I probably confused the intent of this pull request mentioning my confusion around service locators.

The intent of this pull request was to correct a mistake in one of the documents.

If we look at the wording given in the main container document:

https://github.com/php-fig/fig-standards/blob/23d0b3e0e522b4c0276ad6ec1eced2884039a389/accepted/PSR-11-container.md?plain=1#L51

And then compare it to the wording the meta container document quotes the main container document as saying:

https://github.com/php-fig/fig-standards/blob/23d0b3e0e522b4c0276ad6ec1eced2884039a389/accepted/PSR-11-container-meta.md?plain=1#L76

They don't match and it just seems like it was a mistake for the main container document to have the wording as something that is very difficult to understand while the meta document states the information in a way that can be easily understood.

**Comment by ralflang** [comment]
Actually I do not see the difference in meaning between the two wordings. Maybe I am too used to what general advice this section tries to convey.

**Comment by tspencer244** [comment]
This is quite embarrassing but I actually have no idea what I was seeing wrong before. Looking at everything I have posted pictures of, pages linked to, code lines linked to - it all looks fine to me now :sweat_smile: 

I am very sorry for wasting all of your time on this!

Thank you very much for all the effort your team puts into establishing and maintaining these standards, they have really helped to improve the quality of life in my career :slightly_smiling_face:

**Pull request closed without merging**
