### PR TITLE
Rename Linkable to LinkCollection

### PR DESCRIPTION
**Pull request by Crell**
As discussed on the list. I also included a new Design Decision section on why it's included.

### CODE REVIEW

**Comment by localheinz** [comment]
@Crell 

See #717.

**Comment by shadowhand** [comment]
:+1:

**Comment by Crell** [comment]
I will keep repeating: If you file a GitHub issue and don't mention it on the list, no one knows it's there.  It's like a tree falling in the forest.  It didn't actually fall.

**Comment by michaelcullum** [comment]
:+1:

**Comment by Crell** [comment]
Seems no objections here, so merging.

**Pull request merged**
