### PR TITLE
Add example for increment/decrement operators spacing

### PR DESCRIPTION
**Pull request by PowerKiKi**

### CODE REVIEW

**Comment by PowerKiKi** [comment]
I see your point, but IMHO this is not changing the rules established by the spec at all, it is merely a very trivial clarification that really cannot can be misinterpreted.

**Comment by KorvinSzanto** [comment]
I'm not sure that I agree that this clarifies anything, the wording is already super clear. I definitely agree with @Jean85, no changes during voting phase.

**Comment by PowerKiKi** [comment]
rebased

**Comment by goetas** [comment]
Thank you @PowerKiKi

**Pull request merged**
