### PR TITLE
Update HTTP Factory meta document

### PR DESCRIPTION
**Pull request by shadowhand**
Adds comparison of existing approaches in Diactoros, Guzzle, and Slim.

Refs #759

### CODE REVIEW

**Comment by shadowhand** [comment]
@michaelcullum this should address the issues you mentioned in #759.

**Comment by webdevxp** [comment]
@shadowhand I'm trying to implement these interfaces. But I don't understand the part of `StreamFactoryInterface` especially `StreamFactoryInterface::createStreamFromCallback()`.

```
    /**
     * Create a new stream from a callback.
     *
     * The stream will be read-only and not seekable.
     *
     * @param callable $callback
     *
     * @return StreamInterface
     */
    public function createStreamFromCallback(callable $callback);

```
Why callback? And why Stream created from this method will be read-only and not seekable?
Could you please provide more description?

**Comment by webdevxp** [comment]
Should `UploadedFileFactoryInterface` have a method to create array tree of `UploadedFileInterface` from source array ( for example `$_FILES`)?

**Comment by pmjones** [comment]
Ping -- is this ready for merge?

**Comment by shadowhand** [comment]
I believe so, I was just waiting for @michaelcullum to check it.

**Comment by michaelcullum** [comment]
Sorry yes. Thanks @shadowhand.

**Pull request merged**
