### PR TITLE
Add rules on splitting a compound boolean expression / multi-line condition

### PR DESCRIPTION
**Pull request by teohhanhui**
Replaces #900

### CODE REVIEW

**Comment by teohhanhui** [comment]
Yeah, any suggestions on making this DRY?

**Comment by teohhanhui** [comment]
"A compound boolean expression used as the condition in a control structure statement ..."?

**Comment by teohhanhui** [comment]
The problem is how to capture the differences / additional rules when a CBE used as a condition is split across multiple lines. The "base" rules for a CBE being split across multiple lines would still apply.

**Comment by KorvinSzanto** [comment]
There hasn't been any movement on this PR for quite a while so I'm thinking we should close this PR unless someone else would like to take it over and try to make it more approachable.

**Pull request closed without merging**
