### PR TITLE
[PSR4] Translation in italian

### PR DESCRIPTION
**Pull request by Jean85**
After #621, I moved to work on PSR4 for translation.

Please review it! Thanks!

PS: ping to previous reviewers:  @mlocati @eleftrik

### CODE REVIEW

**Comment by gianarb** [comment]
:+1:

**Comment by samdark** [comment]
@gianarb is it good to be merged?

**Comment by gianarb** [comment]
Yes @samdark

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
