### PR TITLE
Swap Beau in as Coordinator.

### PR DESCRIPTION
**Pull request by Crell**
As Paddy has been unavailable for some time, Beau is stepping up to take over the Coordinator position.

### CODE REVIEW

**Comment by simensen** [comment]
Ping @php-fig/maintainers @php-fig/owners Neither @Crell nor myself feel comfortable merging this on our own so we need someone else to do it for us. Thanks!

**Comment by pmjones** [comment]
Honestly I'm not comfortable doing it either. My understanding is that @dragoonis and @tedivm have been critical to the PSR, and if they're not fully supportive, I can't say I'd enjoy stepping on their toes.

**Comment by simensen** [comment]
@pmjones That is fair enough, but @padraic himself blessed this decision.

> I don’t have any objections to a change in the coordinator role – the best of intentions only count when converted into action, and I’ve been unavailable to do so for a couple of months while focused  elsewhere. Being focused elsewhere translates into being impressively invisible online. The PSR is, in any case, well advanced, and I’d already agreed with Larry that it definitely should enter review. I 
don’t see any likely hiccups preventing this rolling all the way to a formal acceptance vote in two weeks once the ball is kicked. 

https://groups.google.com/d/msg/php-fig/4pxjyMPo5kE/g5vzwVW866kJ

**Comment by pmjones** [comment]
I get that @padraic is stepping down of his own free will. Did anyone ask @dragoonis, who has a long history of substantive effort on this PSR, if he wanted to be coordinator?

**Comment by simensen** [comment]
@pmjones I didn't think we needed to involve anyone else as this was simply shifting around people in the existing roles. Especially now that Paddy has now said he has no objections to swapping coordinator/sponsor roles with me I don't see this as being an issue. If you disagree that is your right, but hopefully someone else from @php-fig/maintainers or @php-fig/owners agrees so we can get this merged and finally get this thing into review.

**Comment by pmjones** [comment]
@dragoonis and @tedivm have been offered the opportunity, and have declined, which soothes my concern about good form.

**Pull request merged**
