### PR TITLE
Revert "[PSR-6] Fix exceptions so that they are throwable"

### PR DESCRIPTION
**Pull request by simensen**
Reverts php-fig/fig-standards#596

### CODE REVIEW

**Comment by simensen** [comment]
@Crell if you can merge this revert that would be great.

My post-merge review of this PR was #596 was much quicker than I should have done and that is my bad. Since it was already merged I looked to make sure it wasn't anything substantial and missed the fact that it was changing the interface to a class; based on the diff I thought it was simply making the interfaces PSR-2 compliant by moving the open/close curly braces to their proper location.

My bad for not paying closer attention to this and not doing just a superficial "looks good to me :+1:" post-merge review.

I agree with @tedivm that we should not change history; the revert should be good enough.

**Comment by tedivm** [comment]
:+1:

**Comment by Crell** [comment]
It ought to be just the Coordinator merging things right now, but since he asked specifically...

**Comment by simensen** [comment]
@Crell The reason I asked was being as I was the one who sent the PR.

**Comment by dragoonis** [comment]
I'm on the same page as @simensen - didn't notice the switch from "interface" to "class". Thanks for the spot @Crell 

@Crell did you make this PR manually or did you press the 'Revert' button on the PR page? https://github.com/php-fig/fig-standards/pull/596

**Comment by Crell** [comment]
I pushed the Merge button on this PR.

**Pull request merged**
