### PR TITLE
Errata: StreamableInterface should be StreamInterface

### PR DESCRIPTION
**Pull request by AndrewCarterUK**
Errata: StreamableInterface should be StreamInterface

### CODE REVIEW

**Comment by michaelcullum** [comment]
This is not errata in the usual sense and doesn't strictly need a vote but it should get the editor and coordinator to a-okay it probably. @mwop @simensen

**Comment by AndrewCarterUK** [comment]
@weierophinney 

@michaelcullum you fail at tagging :p

**Comment by weierophinney** [comment]
Ugh, how did I miss those!

I'm not sure if this is errata in terms of requiring a vote, or if we can just merge (as this is clearly a case where we missed updating references when the interface name changed). I, personally, am okay with just merging, as otherwise the text is clearly misleading.

**Comment by AndrewCarterUK** [comment]
Apologies, I didn't realise the word "errata" suggested a vote! (#iamnewhere)

**Comment by michaelcullum** [comment]
@AndrewCarterUK Whoops. I was on my phone so no autocompletion. Thanks.

@weierophinney I think it should be fine as we allow non-breaking typo/formatting fixes to the main standard normally and this is simply an obvious correction to the meta document (not the main standard itself).

**Comment by weierophinney** [comment]
I don't have commit rights, so if somebody who *does* sees this, please merge. :ship:

**Comment by KorvinSzanto** [comment]
:+1:

**Comment by michaelcullum** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/php-fig/PLppetB3PSk

**Comment by Crell** [comment]
Um, @samdark, I specifically wasn't merging yet and asking the list.  (See @michaelcullum's comment.)  Merging right after I tell people that it wouldn't get merged for another day or so is rather rude.

**Comment by samdark** [comment]
I've reacted to https://github.com/php-fig/fig-standards/pull/681#issuecomment-159706833

**Comment by samdark** [comment]
I'm OK reverting it if there will be any objections.

**Pull request merged**
