### PR TITLE
Update PSR-1-basic-coding-standard.md

### PR DESCRIPTION
**Pull request by marcinqunabu**

### CODE REVIEW

**Comment by stefanotorresi** [comment]
hey @marcinqunabu, thanks for the PR, but I must ask, while you're at it, could you please make the heading levels consistent with psr-2 file? i.e. page heading with a single `#`, and the rest scaling down appropriately.

**Comment by marcinqunabu** [comment]
@stefanotorresi I've added consistent heading levels and removed the additional lines

**Comment by stefanotorresi** [comment]
nice, thanks!

**Comment by michaelcullum** [comment]
Thanks!

**Pull request merged**
