### PR TITLE
Apply formatting to all headings in PSR-2 style-guide

### PR DESCRIPTION
**Pull request by danielmatthew**
Hi,

Had attempted to link to `3. Namespace and Use Declarations`, though the lack of a heading meant that this wasn't possible. I've tweaked the formatting slightly to take advantage of what GHFM adds for free…

### CODE REVIEW

**Comment by danielmatthew** [comment]
Thanks for the approves @samdark & @Jean85 !

Anything I can do @afolson @michaelcullum ?

**Comment by jaylinski** [comment]
The proposal https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide-meta.md should also be formatted like this.

**Comment by Aliance** [comment]
Duplicates https://github.com/php-fig/fig-standards/pull/909

**Comment by danielmatthew** [comment]
Happy to close this one if the other gets approved!

**Comment by michaelcullum** [comment]
Thanks!

**Comment by danielmatthew** [comment]
🎉

**Pull request merged**
