### PR TITLE
Rewrote the URI chapter.

### PR DESCRIPTION
**Pull request by evert**
Hi @weierophinney ,

I read the URI chapter again, and I think with all the recent changes, I wasn't super happy about how it was written.

So I attempted to rewrite that paragraph, which hopefully is more clear and reads slightly better. Let me know what you think.

### CODE REVIEW

**Comment by weierophinney** [comment]
Brilliant! Thanks, @evert -- @pmjones, ready to merge!

**Comment by pmjones** [comment]
Hm, 416 won't merge automatically after the recent merges.

**Comment by weierophinney** [comment]
Ping @evert — can you rebase, please?

**Comment by weierophinney** [comment]
#418 rebases this against current master. :)

**Pull request merged**
