### PR TITLE
Add "editor" names on pre-workflow-bylaw PSRs

### PR DESCRIPTION
**Pull request by pmjones**
"Editor" seems the closest correct role for PSRs before the adoption of the workflow bylaw. Happy to entertain challenges to the attribution of editorship on PSRs 0, 1, and 2.

### CODE REVIEW

**Comment by michaelcullum** [comment]
Sure for PSR-1/2.

@Crell @skoop @dzuelke and any others around at PSR-0 inception. Are you agreed the Editor of PSR-0 was Matthew?

@weierophinney Are you happy to accepted PSR-0 editor attribution?

**Comment by weierophinney** [comment]
Jives with my memory; I was the one who came up with the reference implementation that the others signed off on.

**Comment by dzuelke** [comment]
The only thing I remember from PSR-0 times is how angry the numbering scheme made me :p

**Comment by Crell** [comment]
PSR-0 was published before my time, but that's consistent with what I've been told of those wild and woolly days.  AFAIK these changes are accurate as far as retroactive changes go.

**Comment by michaelcullum** [comment]
In which case, I'll merge this then. If anyone has any objections retrospectively then feel free to reach out on the mailing list.

**Comment by pmjones** [comment]
Very good; thanks. Should probably regenerate the php-fig.org site so the changes propagate over to there as well.

**Comment by pmjones** [comment]
@michaelcullum et al: ping ^^

**Comment by michaelcullum** [comment]
@pmjones Ah sorry I missed this. I'm not near a computer today but @svpernova09 will sort it out ASAP

**Comment by svpernova09** [comment]
Sorry for the delay, thanks for the PR. The site has been regenerated.

**Comment by pmjones** [comment]
Nicely done; thanks!

**Pull request merged**
